version: '3.8'
services:
 # MySQL Database
 mysqldb:
   image: mysql:5.7
   restart: unless-stopped
   environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: yes
   ports:
     - 3306:3306
   volumes:
     - db:/var/lib/mysql

 # Spring Boot Application
 devops-app:
   image: khaliladimassi/achat:1.0
   restart: on-failure
   environment:
     MYSQL_ROOT_PASSWORD: root_password
   ports:
     - 8089:8089
   stdin_open: true
   tty: true
   depends_on:
     - mysqldb
volumes:
 db:
# monitoring
 prometheus:
   image: 'prom/prometheus:v2.14.0'
   ports:
     - '9090:9090'
   command: '--config.file=/etc/prometheus/config.yml'
   volumes:
     - './prometheus.yml:/etc/prometheus/config.yml'
 grafana:
   image: 'grafana/grafana:6.5.0'
   ports:
     - '3000:3000'
