version: '3.8'
services:
 # MySQL Database
 mysqldb:
   image: mysql:5.7
   restart: unless-stopped
   environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: yes
   ports:
     - 3306:3306
   volumes:
     - db:/var/lib/mysql

 # Spring Boot Application
 devops-app:
   image: khaliladimassi/achat:1.0
   restart: on-failure
   environment:
     MYSQL_ROOT_PASSWORD: root_password
   ports:
     - 8089:8089
   stdin_open: true
   tty: true
   depends_on:
     - mysqldb
volumes:
 db:
