version: '3.8'
services:
 # MySQL Database
 mysqldb:
   image: mysql:5.7
   restart: unless-stopped
   environment:
     MYSQL_ROOT_PASSWORD: root_password
   ports:
     - 3306:3306 # Map the container's port 3306 to host port 3306
   volumes:
     - db:/var/lib/mysql
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   command: --default-authentication-plugin=mysql_native_password

 # Spring Boot Application
 devops-app:
   image: khaliladimassi/achat-1.0:latest # Replace with your Spring Boot image
   restart: on-failure
   environment:
     MYSQL_ROOT_PASSWORD: root_password
     SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD:
   ports:
     - 8085:8085
   stdin_open: true
   tty: true
   depends_on:
     - mysqldb
volumes:
 db:
