version: '3.8'
services:
  # MySQL Database
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306  # Map the container's port 3306 to host port 3306
    volumes:
      - db:/var/lib/mysql

  # Spring Boot Application
  devops-app:
    image: khaliladimassi/achat-1.0:latest  # Replace with your Spring Boot image
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 8090:8090  # Map the container's port 8090 to host port 8090
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
volumes:
  db:
