version: '3.8'
services:
 mysqldb:
   container_name: mysql_db
   image: mysql:5.7
   restart: unless-stopped
   environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: yes
   ports:
     - 3306:3306
   volumes:
     - db:/var/lib/mysql

 devops-app:
   container_name: achat_app
   image: khaliladimassi/achat:1.0
   restart: on-failure
   environment:
     MYSQL_ROOT_PASSWORD: root_password
   ports:
     - 8089:8089
   stdin_open: true
   tty: true
   depends_on:
     - mysqldb

 prometheus:
   container_name: prometheus
   image: 'prom/prometheus:latest'
   ports:
     - '9090:9090'
   command: '--config.file=/etc/prometheus/config.yml'
   volumes:
     - './prometheus.yml:/etc/prometheus/config.yml'

 grafana:
   container_name: grafana
   image: 'grafana/grafana:latest'
   ports:
     - '3000:3000'

volumes:
 db:
